- name: Install Apache
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Ensure Apache is started and enabled
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true

