---
- name: Apache config on multi-OS
  hosts: all
  become: yes
  tasks:
    - name: Ensure Apache is installed
      package:
        name: "{{ apache_pkg }}"
        state: present
  vars:
    apache_pkg: "{{ 'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}"

