---
- name: Install Apache
  hosts: web
  become: yes
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

- name: Deploy Static Web Page
  hosts: web
  become: yes
  tasks:
    - name: Copy HTML
      copy:
        content: "<h1>Multi Playbook HTML</h1>"
        dest: /var/www/html/index.html

